// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:7ccdf95b-4759-422b-a2da-95237f97c3dd',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_UJDL6vQ29',
  aws_user_pools_web_client_id: '6tuhtsgjm4l43i5179cla27ebn',
  oauth: {},
};

export default awsmobile;
