// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:a2eb48fc-6f49-49a1-b111-fd3482f80043',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_suNGk8GOZ',
  aws_user_pools_web_client_id: '5u2cgop5aghadug1do59rp8s5o',
  oauth: {},
};

export default awsmobile;
